version: 1.0.{build}

# Используем образ
image: Ubuntu

# Установка Node.js
environment:
  nodejs_version: "20.14.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install -g yarn

# Установка зависимостей
build_script:
  - yarn
  - yarn build

# Линтинг и тестирование
test_script:
  - yarn lint
  - yarn test

# Деплой
deploy_script:
  - git config --global user.name "AppVeyor"
  - git config --global user.email "ci@appveyor.com"
  - git remote set-url origin https://$GITHUB_TOKEN:x-oauth-basic@github.com/Jekarobot/dom.git
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
