version: 1.0.{build}

image: Ubuntu

environment:
  nodejs_version: "20.14.0"

install:
  - >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash &&
    export NVM_DIR="$HOME/.nvm" &&
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" &&
    nvm install $nodejs_version &&
    nvm use $nodejs_version &&
    node --version &&
    npm --version &&
    npm install -g yarn

build_script:
  - yarn
  - yarn build

test_script:
  - yarn lint
  - yarn test

deploy_script:
  - git config --global user.name "AppVeyor"
  - git config --global user.email "ci@appveyor.com"
  - git remote set-url origin https://$GITHUB_TOKEN:x-oauth-basic@github.com/Jekarobot/dom.git
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
